DROP TABLE Customer;
DELETE FROM Customer WHERE cid=1003;
CREATE TABLE Customer(
	cid			BIGINT			PRIMARY KEY AUTO_INCREMENT,
	email		VARCHAR(20)		NOT NULL,
	passwd		VARCHAR(20)		NOT NULL,
	name		VARCHAR(20)		NOT NULL,
	ssn			VARCHAR(14)		NOT NULL, -- 920234-2345678
	phone 		VARCHAR(13)		NOT NULL, -- 010-2345-2345
	regDate		TIMESTAMP		NOT NULL	DEFAULT CURRENT_TIMESTAMP
)AUTO_INCREMENT = 1001;

SELECT * FROM Customer


DROP TABLE Account;
CREATE TABLE Account(
	aid				BIGINT			PRIMARY KEY AUTO_INCREMENT,
	customerId 		BIGINT			NOT NULL,
	accountNum 		CHAR(9)			NOT NULL, -- 000-00-0000
	accType 		CHAR(1) 		NOT NULL DEFAULT 'S',
	balance 		DOUBLE 			NOT NULL DEFAULT 0.0,
	interestRate 	DOUBLE 			NOT NULL DEFAULT 0.0,
	overDraft 		DOUBLE 			NOT NULL DEFAULT 0.0,
	regDate 		TIMESTAMP 		NOT NULL DEFAULT CURRENT_TIMESTAMP,
	
	CONSTRAINT Account_customerId_FK
		FOREIGN KEY(customerId) REFERENCES Customer(cid)
)AUTO_INCREMENT = 3001;

SELECT * FROM Account;




DROP TABLE MenuItems;
CREATE TABLE MenuItems(
	itemName 		VARCHAR(20)		PRIMARY KEY,
	price			DOUBLE			NOT NULL DEFAULT 0.0,
	quantity		DOUBLE			NOT NULL DEFAULT 0.0,
);
SELECT * FROM MenuItems;


CREATE TABLE Oder(
	customerId		BIGINT			NOT NULL,
	oderNum 		NUMBER(5)		PRIMARY KEY,
	regDate 		TIMESTAMP 		NOT NULL DEFAULT CURRENT_TIMESTAMP
);
SELECT * FROM Oder;


CREATE TABLE DetailOder(
	oderNum 		NUMBER(5)		PRIMARY KEY,
	espresso        NUMBER(4)
);
SELECT * FROM DetailOder;


